# Generated by Django 3.0.4 on 2020-05-15 09:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('myid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('stati', models.IntegerField(default=1, verbose_name='状态')),
                ('valid', models.BooleanField(default=1, verbose_name='是否合法')),
            ],
            options={
                'verbose_name_plural': '权限管理',
            },
        ),
        migrations.CreateModel(
            name='Communities',
            fields=[
                ('myid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='社区名')),
                ('province', models.CharField(max_length=100, null=True, verbose_name='省市')),
                ('address', models.TextField(null=True, verbose_name='地址')),
                ('deadline', models.DateTimeField(auto_now_add=True, verbose_name='截止时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('in_code', models.CharField(default='0', max_length=100, null=True, verbose_name='邀请码')),
                ('stati', models.IntegerField(default=1, verbose_name='状态')),
                ('valid', models.BooleanField(default=1, verbose_name='是否合法')),
            ],
            options={
                'verbose_name_plural': '社区管理',
            },
        ),
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('myid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, verbose_name='类型名')),
                ('type_id', models.IntegerField(default=0, verbose_name='类型ID')),
                ('tn', models.CharField(max_length=30, null=True, verbose_name='类型英文名')),
                ('stati', models.IntegerField(default=1, verbose_name='状态')),
                ('valid', models.BooleanField(default=1, verbose_name='是否合法')),
            ],
            options={
                'verbose_name_plural': '商品类型管理',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('myid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('name', models.CharField(default='', max_length=50, verbose_name='英文名')),
                ('authority', models.TextField(max_length=100, verbose_name='权限')),
                ('stati', models.IntegerField(default=1, verbose_name='状态')),
                ('valid', models.BooleanField(default=1, verbose_name='是否合法')),
            ],
            options={
                'verbose_name_plural': '角色管理',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('myid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('vatara', models.CharField(max_length=50, null=True)),
                ('community_id', models.CharField(max_length=50, null=True, verbose_name='社区ID')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('gender', models.IntegerField(default=0, verbose_name='性别')),
                ('occupation', models.CharField(max_length=50, verbose_name='职业')),
                ('specialty', models.TextField(verbose_name='特长')),
                ('content', models.TextField(verbose_name='人物简介')),
                ('contact', models.CharField(max_length=50, verbose_name='联系方式')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.CharField(default='0', max_length=50, verbose_name='账号')),
                ('password', models.CharField(default='0', max_length=50, verbose_name='密码')),
                ('role', models.CharField(default='general_user', max_length=50, verbose_name='角色')),
                ('role_weight', models.IntegerField(default=1, verbose_name='角色权重')),
                ('zupu_key', models.CharField(default='0', max_length=100, verbose_name='族谱key')),
                ('openid', models.CharField(default='0', max_length=100, verbose_name='openid')),
                ('mate', models.CharField(default='0', max_length=50, verbose_name='配偶')),
                ('stati', models.IntegerField(default=1, verbose_name='状态')),
                ('valid', models.BooleanField(default=1, verbose_name='是否合法')),
            ],
            options={
                'verbose_name_plural': '用户管理',
            },
        ),
        migrations.CreateModel(
            name='Volun_activity',
            fields=[
                ('myid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=600, null=True, verbose_name='标题')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(auto_now_add=True, verbose_name='结束时间')),
                ('deadline', models.DateTimeField(default=datetime.datetime(2020, 5, 18, 17, 19, 5, 375787), verbose_name='报名截止')),
                ('description', models.TextField(null=True, verbose_name='描述')),
                ('plan', models.TextField(verbose_name='计划')),
                ('img', models.TextField(null=True, verbose_name='主图')),
                ('need_number', models.IntegerField(default=1, verbose_name='需要人数')),
                ('stati', models.IntegerField(default=1, verbose_name='状态')),
                ('valid', models.BooleanField(default=1, verbose_name='是否合法')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityApp.Communities', verbose_name='社区')),
                ('create_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_person_VolunLeader', to='communityApp.Users', verbose_name='创建人')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_VolunLeader', to='communityApp.Users', verbose_name='队长')),
            ],
            options={
                'verbose_name_plural': '志愿活动管理',
            },
        ),
        migrations.CreateModel(
            name='zupu_level',
            fields=[
                ('myid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_key', models.CharField(max_length=50, verbose_name='族谱key')),
                ('name', models.CharField(max_length=50, verbose_name='标题')),
                ('dai', models.IntegerField(default=1, verbose_name='代数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('stati', models.IntegerField(default=1, verbose_name='状态')),
                ('valid', models.BooleanField(default=1, verbose_name='是否合法')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityApp.Communities', verbose_name='社区')),
                ('create_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityApp.Users', verbose_name='创建人')),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('user_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='communityApp.Users', verbose_name='用户')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('phone', models.CharField(max_length=50, verbose_name='手机号')),
                ('community_id', models.IntegerField(default=0, verbose_name='社区号')),
                ('stati', models.IntegerField(default=1, verbose_name='状态')),
                ('valid', models.BooleanField(default=1, verbose_name='是否合法')),
            ],
            options={
                'verbose_name_plural': '社区管理员',
            },
        ),
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('user_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='communityApp.Users', verbose_name='用户')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('activtiy', models.TextField(null=True, verbose_name='参与活动')),
                ('stati', models.IntegerField(default=1, verbose_name='状态')),
                ('valid', models.BooleanField(default=1, verbose_name='是否合法')),
            ],
            options={
                'verbose_name_plural': '志愿者管理',
            },
        ),
        migrations.CreateModel(
            name='zupu_relationship',
            fields=[
                ('myid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('xh', models.IntegerField(default=1, verbose_name='排序')),
                ('parent', models.CharField(max_length=100, verbose_name='父辈ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('stati', models.IntegerField(default=1, verbose_name='状态')),
                ('valid', models.BooleanField(default=1, verbose_name='是否合法')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityApp.Communities', verbose_name='社区')),
                ('dai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityApp.zupu_level', verbose_name='代数')),
                ('info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='communityApp.Users', verbose_name='详细信息')),
            ],
        ),
        migrations.CreateModel(
            name='zupu_people',
            fields=[
                ('myid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatara', models.CharField(max_length=100, verbose_name='头像')),
                ('zupu_key', models.CharField(max_length=100, verbose_name='族谱key')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.IntegerField(default=0, verbose_name='性别')),
                ('imgs', models.TextField(max_length=100, verbose_name='相关图片')),
                ('content', models.TextField(max_length=100, verbose_name='人物简介')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('mate', models.IntegerField(default=0, verbose_name='状态')),
                ('stati', models.IntegerField(default=1, verbose_name='状态')),
                ('valid', models.BooleanField(default=1, verbose_name='是否合法')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityApp.Communities', verbose_name='社区')),
            ],
        ),
        migrations.CreateModel(
            name='Volun_activity_d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('reason', models.TextField(null=True, verbose_name='原因')),
                ('job', models.CharField(max_length=50, null=True, verbose_name='工作')),
                ('my_start_time', models.DateTimeField(auto_now_add=True, verbose_name='我的开始时间')),
                ('my_end_time', models.DateTimeField(auto_now_add=True, verbose_name='我的结束时间')),
                ('stati', models.IntegerField(default=1, verbose_name='状态')),
                ('valid', models.BooleanField(default=1, verbose_name='是否合法')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityApp.Volun_activity', verbose_name='活动')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityApp.Users', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '活动详情',
            },
        ),
        migrations.CreateModel(
            name='Respects',
            fields=[
                ('myid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('avatar', models.CharField(max_length=50, null=True, verbose_name='头像')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('gender', models.IntegerField(default=0, verbose_name='性别')),
                ('live_situation', models.CharField(max_length=100, verbose_name='居住状态')),
                ('health_situation', models.CharField(max_length=100, verbose_name='身体状态')),
                ('address', models.CharField(max_length=100, verbose_name='住址')),
                ('single', models.CharField(max_length=20, null=True, verbose_name='是否丧偶')),
                ('hobby', models.TextField(max_length=600, null=True, verbose_name='爱好')),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='电话号码')),
                ('families', models.CharField(max_length=50, null=True, verbose_name='紧急联系人')),
                ('family_call', models.CharField(max_length=50, verbose_name='联系人号码')),
                ('note', models.TextField(null=True, verbose_name='备注')),
                ('prove_num', models.IntegerField(default=0, verbose_name='证实数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('stati', models.IntegerField(default=1, verbose_name='状态')),
                ('valid', models.BooleanField(default=1, verbose_name='是否合法')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityApp.Communities', verbose_name='社区')),
                ('publish_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityApp.Users', verbose_name='发布人')),
            ],
            options={
                'verbose_name_plural': '老人管理',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('myid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='价格')),
                ('unit', models.CharField(max_length=26, verbose_name='单位')),
                ('inventory', models.IntegerField(default=1)),
                ('start_price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='起卖价')),
                ('phone', models.CharField(max_length=26, verbose_name='号码')),
                ('contact_type', models.CharField(max_length=50, verbose_name='联系方式')),
                ('note', models.TextField(max_length=600, null=True, verbose_name='备注')),
                ('get_type', models.CharField(default='1', max_length=26, verbose_name='送货方式')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('stati', models.IntegerField(default=1, verbose_name='状态')),
                ('valid', models.BooleanField(default=1, verbose_name='是否合法')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityApp.Communities', verbose_name='社区')),
                ('publish_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityApp.Users', verbose_name='发布人')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityApp.Product_type', verbose_name='类型')),
            ],
            options={
                'verbose_name_plural': '商品管理',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='图片路径')),
                ('title', models.TextField(max_length=100, verbose_name='标题')),
                ('type', models.CharField(default='proDetail', max_length=20, verbose_name='类别')),
                ('valid', models.BooleanField(default=1, verbose_name='是否合法')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityApp.Products', verbose_name='商品')),
            ],
            options={
                'verbose_name_plural': '图片管理',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dai_number', models.IntegerField(default=0, verbose_name='代数')),
                ('married', models.IntegerField(default=0, verbose_name='是否婚配')),
                ('mate', models.CharField(max_length=20, verbose_name='配偶')),
                ('parent', models.CharField(max_length=50, verbose_name='父母')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('stati', models.IntegerField(default=1, verbose_name='状态')),
                ('valid', models.BooleanField(default=1, verbose_name='是否合法')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityApp.Communities', verbose_name='社区')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityApp.Users', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '家族家族',
            },
        ),
        migrations.CreateModel(
            name='Confirm_people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('valid', models.BooleanField(default=1, verbose_name='是否合法')),
                ('respect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityApp.Respects', verbose_name='老人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityApp.Users', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '证实管理',
            },
        ),
        migrations.AddField(
            model_name='communities',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Users_administrator', to='communityApp.Users', verbose_name='社区管理人'),
        ),
        migrations.AddField(
            model_name='communities',
            name='create_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Users_create_person', to='communityApp.Users', verbose_name='创建人'),
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('stati', models.IntegerField(default=1, verbose_name='状态')),
                ('valid', models.BooleanField(default=1, verbose_name='是否合法')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='communityApp.zupu_relationship', verbose_name='孩子ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='father', to='communityApp.zupu_relationship', verbose_name='父亲ID')),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.TextField(verbose_name='特长')),
                ('reason', models.TextField(verbose_name='原因')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('stati', models.IntegerField(default=1, verbose_name='状态')),
                ('valid', models.BooleanField(default=1, verbose_name='是否合法')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityApp.Users', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '志愿申请',
            },
        ),
        migrations.CreateModel(
            name='Activty_respects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stati', models.IntegerField(default=1, verbose_name='状态')),
                ('valid', models.BooleanField(default=1, verbose_name='是否合法')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityApp.Volun_activity', verbose_name='参与活动')),
                ('respect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityApp.Respects', verbose_name='老人')),
            ],
            options={
                'verbose_name_plural': '参与活动老人',
            },
        ),
        migrations.CreateModel(
            name='Volun_leader',
            fields=[
                ('user_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_info_User', serialize=False, to='communityApp.Users', verbose_name='用户')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('stati', models.IntegerField(default=0, verbose_name='状态')),
                ('valid', models.BooleanField(default=1, verbose_name='是否合法')),
                ('add_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_person_User', to='communityApp.Users', verbose_name='添加人')),
            ],
            options={
                'verbose_name_plural': '队长管理',
            },
        ),
    ]
