# Generated by Django 3.0.4 on 2020-05-20 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volun_activity',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 14, 42, 50, 592637), verbose_name='报名截止'),
        ),
    ]
